const fs=require('node:fs');
const path=require('node:path');
const {before,after,afterEach,test}=require('node:test');
const {assertFails,assertSucceeds,initializeTestEnvironment}=require('@firebase/rules-unit-testing');
const {doc,getDoc,setDoc,updateDoc,deleteDoc,serverTimestamp}=require('firebase/firestore');
const PROJECT_ID='aspirenest-rules-test';
const ADMIN_EMAIL='aspirenestplatform@gmail.com';
const STUDENT_EMAIL='student@example.com';
let env;
const addr=()=>{const raw=process.env.FIRESTORE_EMULATOR_HOST||'127.0.0.1:8080';const [host,port]=raw.split(':');return {host,port:Number(port)}};
before(async()=>{const {host,port}=addr();env=await initializeTestEnvironment({projectId:PROJECT_ID,firestore:{host,port,rules:fs.readFileSync(path.resolve(__dirname,'../../firestore.rules'),'utf8')}})});
afterEach(async()=>{await env.clearFirestore()});after(async()=>{await env.cleanup()});
const db=(uid,email)=>env.authenticatedContext(uid,{email}).firestore();
const student=()=>db('student-uid',STUDENT_EMAIL);const other=()=>db('other-uid','other@example.com');const admin=()=>db('admin-uid',ADMIN_EMAIL);
const requestPayload=()=>({requestId:'req-1',requesterType:'student',uid:'student-uid',learnerId:'student-uid',learnerEmail:STUDENT_EMAIL,normalizedEmail:STUDENT_EMAIL,resourceId:'test-1',resourceType:'test',moduleKey:'mockTest',itemType:'mockTest',title:'Exact Test',canonicalRoute:'/ctet-tet/mock-tests/start/test-1',requiredPlan:'PREMIUM',scopeType:'item',target:'test-1',itemIds:[],reason:'Need exact test access',message:'',targetExam:'CTET',status:'submitted',grantId:null,adminNote:'',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});
test('student creates own request but cannot self approve',async()=>{await assertSucceeds(setDoc(doc(student(),'studentAccessRequests/req-1'),requestPayload()));await assertSucceeds(getDoc(doc(student(),'studentAccessRequests/req-1')));await assertFails(updateDoc(doc(student(),'studentAccessRequests/req-1'),{status:'approved',grantId:'grant-1'}));});
test('cross student cannot read request and admin can update',async()=>{await env.withSecurityRulesDisabled(async(c)=>setDoc(doc(c.firestore(),'studentAccessRequests/req-1'),{...requestPayload(),createdAt:new Date(),updatedAt:new Date()}));await assertFails(getDoc(doc(other(),'studentAccessRequests/req-1')));await assertSucceeds(updateDoc(doc(admin(),'studentAccessRequests/req-1'),{status:'approved',grantId:'grant-1',updatedAt:serverTimestamp()}));});
test('authoritative studentAccess cannot hard delete',async()=>{await env.withSecurityRulesDisabled(async(c)=>setDoc(doc(c.firestore(),'studentAccess/grant-1'),{uid:'student-uid',email:STUDENT_EMAIL,normalizedEmail:STUDENT_EMAIL,status:'blocked'}));await assertFails(deleteDoc(doc(admin(),'studentAccess/grant-1')));});
test('access notification is own-read and admin-write only',async()=>{await assertSucceeds(setDoc(doc(admin(),'accessNotifications/n-1'),{uid:'student-uid',email:STUDENT_EMAIL,audience:'student',event:'access_request_approved',title:'Access approved',copy:'Exact item active',requestId:'req-1',status:'unread',createdAt:serverTimestamp(),updatedAt:serverTimestamp()}));await assertSucceeds(getDoc(doc(student(),'accessNotifications/n-1')));await assertFails(getDoc(doc(other(),'accessNotifications/n-1')));await assertFails(updateDoc(doc(student(),'accessNotifications/n-1'),{status:'read'}));});
